import { motion } from 'framer-motion'
import {
  FileText, GitBranch, Rocket, Users, ShoppingCart, ArrowRight, Bug, Lightbulb,
  Receipt, Headphones, Megaphone, PenTool, UserPlus, BarChart3, Target, Trophy,
  Package, RotateCcw, DollarSign,
} from 'lucide-react'

const C = {
  bg: '#05050A',
  card: '#090914',
  cardBdr: 'rgba(255,255,255,0.06)',
  cyan: '#00D2FF',
  text: '#f1f5f9',
  muted: '#6b7280',
}

const TEMPLATES = [
  {
    id: 'blank',
    label: 'Blank Canvas',
    description: 'Start from scratch',
    icon: FileText,
    color: '#6b7280',
    tags: [],
    connections: [],
  },
  {
    id: 'cicd-pipeline',
    label: 'CI/CD Pipeline',
    description: 'Commit -> Build -> Test -> Stage -> Deploy -> Monitor',
    icon: Rocket,
    color: '#34D399',
    tags: [
      { id: '1', text: 'Code Commit', x: 260, y: 40, shape: 'stadium', duration: '0', cost: '0', department: '', app: 'slack' },
      { id: '2', text: 'Build & Lint', x: 260, y: 140, shape: 'rectangle', duration: '5m', cost: '50', department: 'engineering', app: '' },
      { id: '3', text: 'Run Tests', x: 260, y: 240, shape: 'rectangle', duration: '10m', cost: '100', department: 'engineering', app: '' },
      { id: '4', text: 'Tests Pass?', x: 260, y: 340, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '5', text: 'Deploy to Staging', x: 80, y: 440, shape: 'rectangle', duration: '5m', cost: '200', department: 'engineering', app: 'zapier' },
      { id: '6', text: 'Notify Failure', x: 440, y: 440, shape: 'cloud', duration: '0', cost: '0', department: 'engineering', app: 'slack' },
      { id: '7', text: 'QA Review', x: 80, y: 540, shape: 'rectangle', duration: '2h', cost: '300', department: 'engineering', app: '' },
      { id: '8', text: 'Deploy to Production', x: 80, y: 640, shape: 'rectangle', duration: '10m', cost: '500', department: 'operations', app: 'zapier' },
      { id: '9', text: 'Health Monitor', x: 80, y: 740, shape: 'cylinder', duration: '15m', cost: '0', department: 'operations', app: '' },
      { id: '10', text: 'Pipeline Complete', x: 80, y: 840, shape: 'stadium', duration: '0', cost: '0', department: '', app: '' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '4', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '4', to: '5', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '4', to: '6', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '5', to: '7', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '7', to: '8', fromPort: 'bottom', toPort: 'top', label: 'Pass' },
      { from: '8', to: '9', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '9', to: '10', fromPort: 'bottom', toPort: 'top', label: '' },
    ],
  },
  {
    id: 'bug-fix',
    label: 'Bug Fix Workflow',
    description: 'Report -> Triage -> Critical? -> Hotfix/Backlog -> Fix -> Review -> Deploy',
    icon: Bug,
    color: '#EF4444',
    tags: [
      { id: '1', text: 'Bug Reported', x: 260, y: 40, shape: 'stadium', duration: '0', cost: '0', department: 'operations', app: 'hubspot' },
      { id: '2', text: 'Triage & Prioritize', x: 260, y: 140, shape: 'rectangle', duration: '30m', cost: '0', department: 'engineering', app: '' },
      { id: '3', text: 'Critical Bug?', x: 260, y: 240, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '4', text: 'Hotfix Branch', x: 80, y: 340, shape: 'rectangle', duration: '1h', cost: '200', department: 'engineering', app: '' },
      { id: '5', text: 'Schedule for Sprint', x: 440, y: 340, shape: 'rectangle', duration: '0', cost: '0', department: 'engineering', app: 'hubspot' },
      { id: '6', text: 'Implement Fix', x: 260, y: 440, shape: 'rectangle', duration: '4h', cost: '500', department: 'engineering', app: '' },
      { id: '7', text: 'Code Review', x: 260, y: 540, shape: 'rectangle', duration: '2h', cost: '200', department: 'engineering', app: 'slack' },
      { id: '8', text: 'Review Approved?', x: 260, y: 640, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '9', text: 'Deploy Fix', x: 80, y: 740, shape: 'rectangle', duration: '15m', cost: '100', department: 'operations', app: 'zapier' },
      { id: '10', text: 'Verify in Prod', x: 80, y: 840, shape: 'rectangle', duration: '1h', cost: '0', department: 'engineering', app: 'hubspot' },
      { id: '11', text: 'Bug Resolved', x: 80, y: 940, shape: 'stadium', duration: '0', cost: '0', department: '', app: '' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '4', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '3', to: '5', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '4', to: '6', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '5', to: '6', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '6', to: '7', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '7', to: '8', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '8', to: '9', fromPort: 'bottom', toPort: 'top', label: 'Approved' },
      { from: '8', to: '7', fromPort: 'right', toPort: 'right', label: 'Revise' },
      { from: '9', to: '10', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '10', to: '11', fromPort: 'bottom', toPort: 'top', label: '' },
    ],
  },
  {
    id: 'feature-request',
    label: 'Feature Request',
    description: 'Request -> Requirements -> Feasibility -> Design -> Build -> Ship',
    icon: Lightbulb,
    color: '#3B82F6',
    tags: [
      { id: '1', text: 'Feature Request', x: 260, y: 40, shape: 'stadium', duration: '0', cost: '0', department: 'operations', app: 'hubspot' },
      { id: '2', text: 'Gather Requirements', x: 260, y: 140, shape: 'parallelogram', duration: '2d', cost: '500', department: 'operations', app: '' },
      { id: '3', text: 'Feasibility Check', x: 260, y: 240, shape: 'diamond', duration: '1d', cost: '200', department: 'engineering', app: '' },
      { id: '4', text: 'Design Document', x: 80, y: 340, shape: 'document', duration: '3d', cost: '1000', department: 'operations', app: '' },
      { id: '5', text: 'Decline Request', x: 440, y: 340, shape: 'rectangle', duration: '0', cost: '0', department: 'operations', app: 'gmail' },
      { id: '6', text: 'Development Sprint', x: 80, y: 440, shape: 'rectangle', duration: '10d', cost: '15000', department: 'engineering', app: '' },
      { id: '7', text: 'QA Testing', x: 80, y: 540, shape: 'rectangle', duration: '3d', cost: '2000', department: 'engineering', app: '' },
      { id: '8', text: 'Ready to Ship?', x: 80, y: 640, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '9', text: 'Release Notes', x: 80, y: 740, shape: 'document', duration: '1d', cost: '0', department: 'marketing', app: 'gmail' },
      { id: '10', text: 'Fix Issues', x: 440, y: 640, shape: 'rectangle', duration: '2d', cost: '1000', department: 'engineering', app: '' },
      { id: '11', text: 'Launch Feature', x: 80, y: 840, shape: 'cloud', duration: '1d', cost: '200', department: 'engineering', app: 'zapier' },
      { id: '12', text: 'Feature Live', x: 80, y: 940, shape: 'stadium', duration: '0', cost: '0', department: '', app: '' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '4', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '3', to: '5', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '4', to: '6', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '6', to: '7', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '7', to: '8', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '8', to: '9', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '8', to: '10', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '10', to: '7', fromPort: 'top', toPort: 'right', label: '' },
      { from: '9', to: '11', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '11', to: '12', fromPort: 'bottom', toPort: 'top', label: '' },
    ],
  },
  {
    id: 'invoice-processing',
    label: 'Invoice Processing',
    description: 'Receive -> Verify -> PO Match -> Approve -> Pay -> Record',
    icon: Receipt,
    color: '#8B5CF6',
    tags: [
      { id: '1', text: 'Receive Invoice', x: 260, y: 40, shape: 'parallelogram', duration: '0', cost: '0', department: 'finance', app: '' },
      { id: '2', text: 'Enter & Verify', x: 260, y: 140, shape: 'rectangle', duration: '30m', cost: '0', department: 'finance', app: '' },
      { id: '3', text: 'PO Matched?', x: 260, y: 240, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '4', text: 'Flag Discrepancy', x: 440, y: 340, shape: 'rectangle', duration: '1d', cost: '0', department: 'finance', app: 'gmail' },
      { id: '5', text: 'Manager Approve', x: 80, y: 340, shape: 'rectangle', duration: '1d', cost: '50', department: 'finance', app: 'slack' },
      { id: '6', text: 'Approved?', x: 80, y: 440, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '7', text: 'Process Payment', x: 80, y: 540, shape: 'rectangle', duration: '1d', cost: '0', department: 'finance', app: 'stripe' },
      { id: '8', text: 'Reject Invoice', x: 440, y: 440, shape: 'rectangle', duration: '0', cost: '0', department: 'finance', app: 'gmail' },
      { id: '9', text: 'Record in Ledger', x: 80, y: 640, shape: 'cylinder', duration: '1h', cost: '0', department: 'finance', app: '' },
      { id: '10', text: 'Invoice Complete', x: 80, y: 740, shape: 'stadium', duration: '0', cost: '0', department: '', app: '' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '5', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '3', to: '4', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '5', to: '6', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '6', to: '7', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '6', to: '8', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '7', to: '9', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '9', to: '10', fromPort: 'bottom', toPort: 'top', label: '' },
    ],
  },
  {
    id: 'employee-onboarding',
    label: 'Employee Onboarding',
    description: 'Offer -> Paperwork -> Background Check -> Setup -> Orientation -> Review',
    icon: Users,
    color: '#EC4899',
    tags: [
      { id: '1', text: 'Offer Accepted', x: 260, y: 40, shape: 'stadium', duration: '0', cost: '0', department: 'hr', app: '' },
      { id: '2', text: 'Send Welcome Email', x: 260, y: 140, shape: 'rectangle', duration: '1h', cost: '0', department: 'hr', app: 'gmail' },
      { id: '3', text: 'Complete Paperwork', x: 260, y: 240, shape: 'parallelogram', duration: '2d', cost: '200', department: 'hr', app: 'google' },
      { id: '4', text: 'Background Check', x: 260, y: 340, shape: 'rectangle', duration: '5d', cost: '500', department: 'hr', app: '' },
      { id: '5', text: 'Cleared?', x: 260, y: 440, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '6', text: 'Setup Equipment', x: 80, y: 540, shape: 'rectangle', duration: '1d', cost: '2000', department: 'engineering', app: '' },
      { id: '7', text: 'Revoke Offer', x: 440, y: 540, shape: 'rectangle', duration: '0', cost: '0', department: 'hr', app: 'gmail' },
      { id: '8', text: 'Orientation & Training', x: 80, y: 640, shape: 'rectangle', duration: '5d', cost: '3000', department: 'hr', app: 'slack' },
      { id: '9', text: '30-Day Review', x: 80, y: 740, shape: 'diamond', duration: '1h', cost: '0', department: 'hr', app: '' },
      { id: '10', text: 'Welcome Aboard!', x: 80, y: 840, shape: 'stadium', duration: '0', cost: '0', department: '', app: '' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '4', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '4', to: '5', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '5', to: '6', fromPort: 'bottom', toPort: 'top', label: 'Pass' },
      { from: '5', to: '7', fromPort: 'right', toPort: 'left', label: 'Fail' },
      { from: '6', to: '8', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '8', to: '9', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '9', to: '10', fromPort: 'bottom', toPort: 'top', label: 'Pass' },
    ],
  },
  {
    id: 'support-ticket',
    label: 'Customer Support Ticket',
    description: 'Ticket -> Classify -> Prioritize -> Investigate -> Resolve -> Close',
    icon: Headphones,
    color: '#F59E0B',
    tags: [
      { id: '1', text: 'Ticket Created', x: 260, y: 40, shape: 'parallelogram', duration: '0', cost: '0', department: 'operations', app: 'hubspot' },
      { id: '2', text: 'Auto-Classify', x: 260, y: 140, shape: 'rectangle', duration: '0', cost: '0', department: 'operations', app: 'zapier' },
      { id: '3', text: 'Priority Level?', x: 260, y: 240, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '4', text: 'Escalate to Lead', x: 80, y: 340, shape: 'rectangle', duration: '15m', cost: '50', department: 'operations', app: 'slack' },
      { id: '5', text: 'Auto-Response', x: 440, y: 340, shape: 'rectangle', duration: '0', cost: '0', department: 'operations', app: 'gmail' },
      { id: '6', text: 'Investigate Issue', x: 260, y: 440, shape: 'rectangle', duration: '2h', cost: '200', department: 'operations', app: '' },
      { id: '7', text: 'Resolved?', x: 260, y: 540, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '8', text: 'Send Resolution', x: 80, y: 640, shape: 'parallelogram', duration: '30m', cost: '0', department: 'operations', app: 'gmail' },
      { id: '9', text: 'Escalate Further', x: 440, y: 640, shape: 'rectangle', duration: '0', cost: '0', department: 'operations', app: 'slack' },
      { id: '10', text: 'Close Ticket', x: 80, y: 740, shape: 'stadium', duration: '0', cost: '0', department: 'operations', app: 'hubspot' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '4', fromPort: 'bottom', toPort: 'top', label: 'High' },
      { from: '3', to: '5', fromPort: 'right', toPort: 'left', label: 'Low' },
      { from: '4', to: '6', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '5', to: '6', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '6', to: '7', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '7', to: '8', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '7', to: '9', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '8', to: '10', fromPort: 'bottom', toPort: 'top', label: '' },
    ],
  },
  {
    id: 'campaign-launch',
    label: 'Campaign Launch',
    description: 'Brief -> Audience -> Content -> Design -> Approve -> Launch -> Monitor',
    icon: Megaphone,
    color: '#F97316',
    tags: [
      { id: '1', text: 'Campaign Brief', x: 260, y: 40, shape: 'document', duration: '1d', cost: '0', department: 'marketing', app: '' },
      { id: '2', text: 'Define Audience', x: 260, y: 140, shape: 'rectangle', duration: '2d', cost: '500', department: 'marketing', app: '' },
      { id: '3', text: 'Create Content', x: 260, y: 240, shape: 'rectangle', duration: '5d', cost: '3000', department: 'marketing', app: '' },
      { id: '4', text: 'Design Assets', x: 260, y: 340, shape: 'rectangle', duration: '3d', cost: '2000', department: 'marketing', app: '' },
      { id: '5', text: 'Approved?', x: 260, y: 440, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '6', text: 'Revise Assets', x: 440, y: 540, shape: 'rectangle', duration: '2d', cost: '500', department: 'marketing', app: '' },
      { id: '7', text: 'Schedule Launch', x: 80, y: 540, shape: 'rectangle', duration: '1d', cost: '0', department: 'marketing', app: 'hubspot' },
      { id: '8', text: 'Launch Campaign', x: 80, y: 640, shape: 'cloud', duration: '0', cost: '0', department: 'marketing', app: 'zapier' },
      { id: '9', text: 'Monitor Performance', x: 80, y: 740, shape: 'cylinder', duration: '14d', cost: '0', department: 'marketing', app: 'hubspot' },
      { id: '10', text: 'Campaign Complete', x: 80, y: 840, shape: 'stadium', duration: '0', cost: '0', department: '', app: '' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '4', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '4', to: '5', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '5', to: '7', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '5', to: '6', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '6', to: '5', fromPort: 'top', toPort: 'right', label: '' },
      { from: '7', to: '8', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '8', to: '9', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '9', to: '10', fromPort: 'bottom', toPort: 'top', label: '' },
    ],
  },
  {
    id: 'content-pipeline',
    label: 'Content Creation Pipeline',
    description: 'Idea -> Research -> Draft -> Review -> SEO -> Publish -> Promote',
    icon: PenTool,
    color: '#06B6D4',
    tags: [
      { id: '1', text: 'Content Idea', x: 260, y: 40, shape: 'stadium', duration: '0', cost: '0', department: 'marketing', app: '' },
      { id: '2', text: 'Research & Outline', x: 260, y: 140, shape: 'rectangle', duration: '2d', cost: '200', department: 'marketing', app: '' },
      { id: '3', text: 'Write Draft', x: 260, y: 240, shape: 'rectangle', duration: '3d', cost: '1000', department: 'marketing', app: '' },
      { id: '4', text: 'Editor Review', x: 260, y: 340, shape: 'diamond', duration: '1d', cost: '200', department: 'marketing', app: '' },
      { id: '5', text: 'Revise Draft', x: 440, y: 440, shape: 'rectangle', duration: '2d', cost: '500', department: 'marketing', app: '' },
      { id: '6', text: 'SEO Optimization', x: 80, y: 440, shape: 'rectangle', duration: '1d', cost: '200', department: 'marketing', app: '' },
      { id: '7', text: 'Final Approval?', x: 80, y: 540, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '8', text: 'Publish Content', x: 80, y: 640, shape: 'parallelogram', duration: '1h', cost: '0', department: 'marketing', app: 'hubspot' },
      { id: '9', text: 'Promote on Social', x: 80, y: 740, shape: 'rectangle', duration: '1d', cost: '300', department: 'marketing', app: 'slack' },
      { id: '10', text: 'Content Live', x: 80, y: 840, shape: 'stadium', duration: '0', cost: '0', department: '', app: '' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '4', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '4', to: '6', fromPort: 'bottom', toPort: 'top', label: 'Approved' },
      { from: '4', to: '5', fromPort: 'right', toPort: 'left', label: 'Revise' },
      { from: '5', to: '4', fromPort: 'top', toPort: 'right', label: '' },
      { from: '6', to: '7', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '7', to: '8', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '8', to: '9', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '9', to: '10', fromPort: 'bottom', toPort: 'top', label: '' },
    ],
  },
  {
    id: 'hiring-process',
    label: 'Hiring Process',
    description: 'Post Job -> Screen -> Interview -> Technical -> Culture -> Offer -> Hire',
    icon: UserPlus,
    color: '#A855F7',
    tags: [
      { id: '1', text: 'Job Posting Live', x: 260, y: 40, shape: 'stadium', duration: '0', cost: '500', department: 'hr', app: 'hubspot' },
      { id: '2', text: 'Screen Resumes', x: 260, y: 140, shape: 'parallelogram', duration: '3d', cost: '300', department: 'hr', app: '' },
      { id: '3', text: 'Phone Interview', x: 260, y: 240, shape: 'rectangle', duration: '30m', cost: '100', department: 'hr', app: '' },
      { id: '4', text: 'Qualified?', x: 260, y: 340, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '5', text: 'Technical Interview', x: 80, y: 440, shape: 'rectangle', duration: '1h', cost: '300', department: 'engineering', app: 'google' },
      { id: '6', text: 'Reject & Notify', x: 440, y: 440, shape: 'rectangle', duration: '0', cost: '0', department: 'hr', app: 'gmail' },
      { id: '7', text: 'Culture Fit', x: 80, y: 540, shape: 'diamond', duration: '30m', cost: '100', department: '', app: '' },
      { id: '8', text: 'Send Offer', x: 80, y: 640, shape: 'parallelogram', duration: '1d', cost: '0', department: 'hr', app: 'gmail' },
      { id: '9', text: 'Offer Accepted?', x: 80, y: 740, shape: 'diamond', duration: '5d', cost: '0', department: '', app: '' },
      { id: '10', text: 'Begin Onboarding', x: 80, y: 840, shape: 'rectangle', duration: '1d', cost: '0', department: 'hr', app: 'slack' },
      { id: '11', text: 'Position Filled', x: 80, y: 940, shape: 'stadium', duration: '0', cost: '0', department: '', app: '' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '4', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '4', to: '5', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '4', to: '6', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '5', to: '7', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '7', to: '8', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '7', to: '6', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '8', to: '9', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '9', to: '10', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '10', to: '11', fromPort: 'bottom', toPort: 'top', label: '' },
    ],
  },
  {
    id: 'performance-review',
    label: 'Performance Review',
    description: 'Self-Assessment -> Manager Eval -> Calibration -> Decision -> Feedback',
    icon: BarChart3,
    color: '#10B981',
    tags: [
      { id: '1', text: 'Review Period Ends', x: 260, y: 40, shape: 'stadium', duration: '0', cost: '0', department: 'hr', app: '' },
      { id: '2', text: 'Self-Assessment', x: 260, y: 140, shape: 'parallelogram', duration: '3d', cost: '0', department: 'hr', app: 'google' },
      { id: '3', text: 'Manager Evaluation', x: 260, y: 240, shape: 'rectangle', duration: '2d', cost: '200', department: 'hr', app: '' },
      { id: '4', text: 'Calibration Meeting', x: 260, y: 340, shape: 'rectangle', duration: '1d', cost: '500', department: 'hr', app: 'google' },
      { id: '5', text: 'Meets Expectations?', x: 260, y: 440, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '6', text: 'Promotion Track', x: 80, y: 560, shape: 'rectangle', duration: '0', cost: '0', department: 'hr', app: '' },
      { id: '7', text: 'Performance Plan', x: 440, y: 560, shape: 'rectangle', duration: '90d', cost: '0', department: 'hr', app: 'slack' },
      { id: '8', text: 'Share Feedback', x: 260, y: 660, shape: 'parallelogram', duration: '1h', cost: '0', department: 'hr', app: 'slack' },
      { id: '9', text: 'Review Complete', x: 260, y: 760, shape: 'stadium', duration: '0', cost: '0', department: '', app: '' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '4', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '4', to: '5', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '5', to: '6', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '5', to: '7', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '6', to: '8', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '7', to: '8', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '8', to: '9', fromPort: 'bottom', toPort: 'top', label: '' },
    ],
  },
  {
    id: 'lead-qualification',
    label: 'Lead Qualification (BANT)',
    description: 'New Lead -> Research -> Budget -> Authority -> Need -> Timeline -> Qualify',
    icon: Target,
    color: '#6366F1',
    tags: [
      { id: '1', text: 'New Lead', x: 260, y: 40, shape: 'parallelogram', duration: '0', cost: '100', department: 'sales', app: 'hubspot' },
      { id: '2', text: 'Research Company', x: 260, y: 140, shape: 'rectangle', duration: '30m', cost: '0', department: 'sales', app: '' },
      { id: '3', text: 'Has Budget?', x: 260, y: 240, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '4', text: 'Has Authority?', x: 80, y: 340, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '5', text: 'Nurture Sequence', x: 440, y: 240, shape: 'rectangle', duration: '0', cost: '0', department: 'sales', app: 'gmail' },
      { id: '6', text: 'Discovery Call', x: 80, y: 440, shape: 'rectangle', duration: '1h', cost: '100', department: 'sales', app: 'google' },
      { id: '7', text: 'Send Proposal', x: 80, y: 540, shape: 'parallelogram', duration: '2d', cost: '300', department: 'sales', app: 'gmail' },
      { id: '8', text: 'Accepted?', x: 80, y: 640, shape: 'diamond', duration: '5d', cost: '0', department: '', app: '' },
      { id: '9', text: 'Deal Won!', x: 80, y: 740, shape: 'stadium', duration: '0', cost: '0', department: 'finance', app: 'stripe' },
      { id: '10', text: 'Follow Up', x: 440, y: 640, shape: 'rectangle', duration: '7d', cost: '100', department: 'sales', app: 'hubspot' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '4', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '3', to: '5', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '4', to: '6', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '4', to: '5', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '6', to: '7', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '7', to: '8', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '8', to: '9', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '8', to: '10', fromPort: 'right', toPort: 'left', label: 'No' },
    ],
  },
  {
    id: 'deal-closure',
    label: 'Deal Closure',
    description: 'Discovery -> Proposal -> Negotiate -> Legal -> Contract -> Payment',
    icon: Trophy,
    color: '#EAB308',
    tags: [
      { id: '1', text: 'Opportunity Created', x: 260, y: 40, shape: 'stadium', duration: '0', cost: '0', department: 'sales', app: 'hubspot' },
      { id: '2', text: 'Discovery Meeting', x: 260, y: 140, shape: 'rectangle', duration: '1h', cost: '200', department: 'sales', app: 'google' },
      { id: '3', text: 'Proposal Sent', x: 260, y: 240, shape: 'parallelogram', duration: '2d', cost: '500', department: 'sales', app: 'gmail' },
      { id: '4', text: 'Negotiation', x: 260, y: 340, shape: 'rectangle', duration: '5d', cost: '0', department: 'sales', app: '' },
      { id: '5', text: 'Terms Agreed?', x: 260, y: 440, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '6', text: 'Legal Review', x: 80, y: 540, shape: 'rectangle', duration: '3d', cost: '1000', department: 'finance', app: '' },
      { id: '7', text: 'Revise Terms', x: 440, y: 540, shape: 'rectangle', duration: '2d', cost: '0', department: 'sales', app: '' },
      { id: '8', text: 'Contract Signing', x: 80, y: 640, shape: 'parallelogram', duration: '1d', cost: '0', department: 'sales', app: 'stripe' },
      { id: '9', text: 'Payment Received', x: 80, y: 740, shape: 'parallelogram', duration: '0', cost: '0', department: 'finance', app: 'stripe' },
      { id: '10', text: 'Deal Closed', x: 80, y: 840, shape: 'stadium', duration: '0', cost: '0', department: '', app: '' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '4', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '4', to: '5', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '5', to: '6', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '5', to: '7', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '7', to: '4', fromPort: 'top', toPort: 'right', label: '' },
      { from: '6', to: '8', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '8', to: '9', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '9', to: '10', fromPort: 'bottom', toPort: 'top', label: '' },
    ],
  },
  {
    id: 'release-planning',
    label: 'Release Planning',
    description: 'Roadmap -> Feedback -> Prioritize -> Estimate -> Budget -> Plan -> Ship',
    icon: Package,
    color: '#14B8A6',
    tags: [
      { id: '1', text: 'Roadmap Review', x: 260, y: 40, shape: 'stadium', duration: '0', cost: '0', department: 'operations', app: '' },
      { id: '2', text: 'Gather Feedback', x: 260, y: 140, shape: 'parallelogram', duration: '1w', cost: '0', department: 'operations', app: 'slack' },
      { id: '3', text: 'Prioritize Features', x: 260, y: 240, shape: 'rectangle', duration: '2d', cost: '500', department: 'operations', app: '' },
      { id: '4', text: 'Estimate Effort', x: 260, y: 340, shape: 'rectangle', duration: '3d', cost: '1000', department: 'engineering', app: '' },
      { id: '5', text: 'Budget Approved?', x: 260, y: 440, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '6', text: 'Create Release Plan', x: 80, y: 540, shape: 'document', duration: '2d', cost: '500', department: 'operations', app: '' },
      { id: '7', text: 'Re-scope Project', x: 440, y: 540, shape: 'rectangle', duration: '3d', cost: '0', department: 'operations', app: '' },
      { id: '8', text: 'Communicate Plan', x: 80, y: 640, shape: 'parallelogram', duration: '1d', cost: '0', department: 'operations', app: 'slack' },
      { id: '9', text: 'Plan Finalized', x: 80, y: 740, shape: 'stadium', duration: '0', cost: '0', department: '', app: '' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '4', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '4', to: '5', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '5', to: '6', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '5', to: '7', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '7', to: '4', fromPort: 'top', toPort: 'right', label: '' },
      { from: '6', to: '8', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '8', to: '9', fromPort: 'bottom', toPort: 'top', label: '' },
    ],
  },
  {
    id: 'sprint-retro',
    label: 'Sprint Retrospective',
    description: 'Metrics -> What Went Well? -> What Didn\'t? -> Action Items -> Improve',
    icon: RotateCcw,
    color: '#F43F5E',
    tags: [
      { id: '1', text: 'Sprint Complete', x: 260, y: 40, shape: 'stadium', duration: '0', cost: '0', department: 'engineering', app: '' },
      { id: '2', text: 'Collect Metrics', x: 260, y: 140, shape: 'parallelogram', duration: '1d', cost: '0', department: 'engineering', app: 'google' },
      { id: '3', text: 'What Went Well?', x: 260, y: 240, shape: 'rectangle', duration: '1h', cost: '0', department: 'engineering', app: '' },
      { id: '4', text: 'What Didn\'t?', x: 260, y: 340, shape: 'rectangle', duration: '1h', cost: '0', department: 'engineering', app: '' },
      { id: '5', text: 'Action Items?', x: 260, y: 440, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '6', text: 'Assign Owners', x: 80, y: 540, shape: 'rectangle', duration: '30m', cost: '0', department: 'engineering', app: 'slack' },
      { id: '7', text: 'Discuss Further', x: 440, y: 540, shape: 'rectangle', duration: '1h', cost: '0', department: 'engineering', app: '' },
      { id: '8', text: 'Update Backlog', x: 80, y: 640, shape: 'cylinder', duration: '1h', cost: '0', department: 'engineering', app: 'hubspot' },
      { id: '9', text: 'Retro Complete', x: 80, y: 740, shape: 'stadium', duration: '0', cost: '0', department: '', app: '' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '4', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '4', to: '5', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '5', to: '6', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '5', to: '7', fromPort: 'right', toPort: 'left', label: 'No' },
      { from: '7', to: '5', fromPort: 'top', toPort: 'right', label: '' },
      { from: '6', to: '8', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '8', to: '9', fromPort: 'bottom', toPort: 'top', label: '' },
    ],
  },
  {
    id: 'expense-approval',
    label: 'Expense Approval',
    description: 'Submit -> Receipts -> Threshold -> Manager -> Approve -> Pay -> Record',
    icon: DollarSign,
    color: '#8B5CF6',
    tags: [
      { id: '1', text: 'Submit Expense', x: 260, y: 40, shape: 'parallelogram', duration: '5m', cost: '0', department: 'finance', app: 'google' },
      { id: '2', text: 'Upload Receipts', x: 260, y: 140, shape: 'document', duration: '10m', cost: '0', department: 'finance', app: '' },
      { id: '3', text: 'Over $500?', x: 260, y: 240, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '4', text: 'Auto-Approve', x: 80, y: 340, shape: 'rectangle', duration: '0', cost: '0', department: 'finance', app: 'zapier' },
      { id: '5', text: 'Manager Review', x: 440, y: 340, shape: 'rectangle', duration: '2d', cost: '50', department: 'finance', app: 'slack' },
      { id: '6', text: 'Approved?', x: 440, y: 440, shape: 'diamond', duration: '0', cost: '0', department: '', app: '' },
      { id: '7', text: 'Process Reimbursement', x: 260, y: 560, shape: 'rectangle', duration: '1d', cost: '0', department: 'finance', app: 'stripe' },
      { id: '8', text: 'Reject Expense', x: 80, y: 440, shape: 'rectangle', duration: '0', cost: '0', department: 'finance', app: 'gmail' },
      { id: '9', text: 'Record in Ledger', x: 260, y: 660, shape: 'cylinder', duration: '1h', cost: '0', department: 'finance', app: '' },
      { id: '10', text: 'Expense Complete', x: 260, y: 760, shape: 'stadium', duration: '0', cost: '0', department: '', app: '' },
    ],
    connections: [
      { from: '1', to: '2', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '2', to: '3', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '3', to: '4', fromPort: 'bottom', toPort: 'top', label: 'No' },
      { from: '3', to: '5', fromPort: 'right', toPort: 'left', label: 'Yes' },
      { from: '4', to: '7', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '5', to: '6', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '6', to: '7', fromPort: 'bottom', toPort: 'top', label: 'Yes' },
      { from: '6', to: '8', fromPort: 'left', toPort: 'right', label: 'No' },
      { from: '7', to: '9', fromPort: 'bottom', toPort: 'top', label: '' },
      { from: '9', to: '10', fromPort: 'bottom', toPort: 'top', label: '' },
    ],
  },
]

export default function WorkflowTemplates({ onSelect }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
      <span style={{ fontSize: 11, fontWeight: 700, color: C.muted, textTransform: 'uppercase', letterSpacing: '0.3px' }}>
        Templates
      </span>
      {TEMPLATES.map(tmpl => (
        <motion.button
          key={tmpl.id}
          whileHover={{ scale: 1.01 }}
          whileTap={{ scale: 0.98 }}
          onClick={() => onSelect(tmpl.tags, tmpl.connections, tmpl.tags.length + 1)}
          style={{
            display: 'flex', alignItems: 'center', gap: 10,
            padding: '10px 12px', borderRadius: 10,
            border: `1px solid ${C.cardBdr}`,
            background: 'rgba(255,255,255,0.02)',
            cursor: 'pointer', textAlign: 'left',
            transition: 'border-color 0.15s, background 0.15s',
          }}
          onMouseEnter={e => { e.currentTarget.style.borderColor = `${tmpl.color}40`; e.currentTarget.style.background = `${tmpl.color}06` }}
          onMouseLeave={e => { e.currentTarget.style.borderColor = C.cardBdr; e.currentTarget.style.background = 'rgba(255,255,255,0.02)' }}
        >
          <div style={{
            width: 32, height: 32, borderRadius: 8, flexShrink: 0,
            background: `${tmpl.color}15`, border: `1px solid ${tmpl.color}30`,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <tmpl.icon size={15} color={tmpl.color} />
          </div>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ fontSize: 11, fontWeight: 700, color: C.text }}>{tmpl.label}</div>
            <div style={{ fontSize: 9, color: C.muted, lineHeight: 1.3 }}>{tmpl.description}</div>
          </div>
          <ArrowRight size={12} color={C.muted} style={{ flexShrink: 0 }} />
        </motion.button>
      ))}
    </div>
  )
}
